--- 
output_dir: output
data_sources: 
- type: filesystem_unified
  items_root: /
  layouts_root: /

# domain to which this site is deployed
base_url: http://unthinkingly.com

# currently used by logo
site_name: unthinkingly

# number of full featured posts to display on front
featured_count: 0

# number of excerpted posts to display on front
excerpt_count: 1000

# number of other articles to reference at bottom of each article
other_articles_max: 3