--- 
kind: article
created_at: 2005-08-29 16:00:57
title: Godcasting
excerpt: "Ever since the first Vatican broadcast of a sermon on the radio in 1931, there has been little doubt about the power of broadcast media as a part of religious practice."
tags: [podcasting, televangelism, NPR, NYT]
modified_on: 2008-04-05 06:12:24
status: publish
---

Ever since the first Vatican broadcast of a sermon on the radio in 1931, there has been little doubt about the power of broadcast media as a part of religious practice. 

Contemporary "church-theatres" (typically the kind with the lights and music shows) are taking the role of media much more seriously, and it appears that they're adapting to some of the most advanced uses of ICT in the world. In an article in <a href="http://www.nytimes.com/2005/08/29/technology/">today's New York Times</a>, it's noted that individual podcasts from sites like <a href="http://www.theatrechurch.com">theatrechurch.com</a> and <a href="http://www.godcast.com">godcast.com</a> are attracting thousands of subscribers worldwide. That's a number that's relatively unheard of at this point in the podcasting evolution.

What is happening is that these communities, already acclimated to the idea of technology-aided practices, are becoming heavily invested in using everything at their disposal to achieve their mission. 

But I think the point in all this is more than just an impressive development in the religious sector. The willingness of religious groups to adapt to podcasting and other ICT-based forms of community practice means that this is viable -- that this really works. Podcasting and blogging's implications have thus far been clear to a few geeks and technologists, but there is, at least among certain populations, a sense in which these religious communities are making it a reality.  

But if youre thinking of Pat Robertson televangelism, consider the Rev. Dr. Martin Luther King. 

The marches, speeches, meetings of the Civil Rights activism of the 1950s and 1960s -- that was what I would call a serious community. And much of it was deeply spiritual, coming from a critical Black religious movement. 

There is much work to be done in revitalizing the religious fuel for the social justice fire, and, judging from the excitment generated by the current developments in worship, there may be a wealth of underdeveloped resources for doing so in the near future.  ###

<strong>See also</strong>: NPR's article: "<a href="http://www.npr.org/templates/story/story.php?storyId=4780903">Now Playing on MP3: iSermons</a>"